apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: cv1sarsabsim-ambulance-ufe-content
spec:
  microFrontend: cv1sarsabsim-ambulance-ufe
  element: sarsabsim-app 
  attributes:
    - name: base-path
      value: /cv1sarsabsim-ambulance-wl/
    - name: api-base
      value: /cv1sarsabsim-api
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?cv1sarsabsim-ambulance-wl(/.*)?$"