apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: cv1sarsabsim-ambulance-ufe-link
spec:
  microFrontend: polyfea-md-shell # referencia na microfrontend, z ktorého sa načíta element
  element: polyfea-md-app # element, ktorý bude vložený na stránku
  attributes: # atribúty elementu polyfea-md-app
    - name: headline
      value: Projekt cv1sarsabsim
    - name: short-headline
      value: Projekt cv1sarsabsim
    - name: supporting-text
      value: |
        Správa lôžkovej časti nemocnice podľa jednotlivých oddelení a ich aktuálne a plánované obsadenie
    - name: material-icon
      value: home_health
    - name: href # presmerovanie po kliknutí na element polyfea-md-app
      value: ./cv1sarsabsim-ambulance-wl
  priority: 10
  displayRules: # pravidlá, kde sa má element vložiť v obálke
    - anyOf:
      - context-name: applications
      - context-name: rail-content
      - context-name: drawer-content