apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cv1sarsabsim-gitops-repo # v spoločnom klastri je nasadených viacero takýchto objektov
  namespace: wac-hospital
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/JSimko4/sarsabsim-gitops

# ak používate privátny repozitár nezabudnite doplniť autentifikačné údaje
# secretRef:
#    name: cv1sarsabsim-repository-pat