apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv1sarsabsim-ambulance-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /cv1sarsabsim-openapi
            - name: BASE_URL
              value: /cv1sarsabsim-openapi-ui